remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US
title: "Awesome Learning"
description: "Digging through new stuff everyday"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
